version: '3.8'

services:
  db:
    image: postgres:15
    container_name: task_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: task_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: taskdb
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: task_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
